# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RideShareApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RideShareApp
    #For Signin
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    #For DB
    pod 'Firebase/Database'
    #For Autocomplete textbox and maps
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'

end
